### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by stay4cold** [sungerk/DropDownLayout#1]
56 27770-27770/? E/ActivityThread: Failed to inflate
                                                   android.view.InflateException: Binary XML file line #2: Error inflating class org.net.sunger.widget.DropDownLayout
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:816)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:745)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136)
                                                       at sunger.net.org.dropmenu.MainActivity.onCreate(MainActivity.java:41)
                                                       at android.app.Activity.performCreate(Activity.java:5242)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2172)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2268)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:145)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5094)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Constructor.constructNative(Native Method)
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:816) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:745) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136) 
                                                       at sunger.net.org.dropmenu.MainActivity.onCreate(MainActivity.java:41) 
                                                       at android.app.Activity.performCreate(Activity.java:5242) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2172) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2268) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:145) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5094) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.NoSuchMethodError: android.widget.FrameLayout.<init>
                                                       at org.net.sunger.widget.DropDownLayout.<init>(DropDownLayout.java:33)
                                                       at org.net.sunger.widget.DropDownLayout.<init>(DropDownLayout.java:28)
                                                       at org.net.sunger.widget.DropDownLayout.<init>(DropDownLayout.java:24)
                                                       at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:816) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:745) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136) 
                                                       at sunger.net.org.dropmenu.MainActivity.onCreate(MainActivity.java:41) 
                                                       at android.app.Activity.performCreate(Activity.java:5242) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2172) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2268) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:145) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5094) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515)

**Comment by sungerk** [comment]
have you rename the package of DropDownLayout?
